version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n8b0e9r5/voltron-repo
      - echo "Running tests..."
      # Add commands to run your tests here

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t voltronapp .
      - docker tag voltronapp:latest public.ecr.aws/n8b0e9r5/voltron-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/n8b0e9r5/voltron-repo:latest
      
artifacts:
    files: imagedefinitions.json
