version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install unzip -y
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform_1.0.0_linux_amd64.zip
      - mv terraform /usr/local/bin
      - chmod +x /usr/local/bin/terraform
      - terraform -v

  pre_build:
    commands:
      - cd MVP  # Navigate to the MVP folder
      - echo "Running Terraform Init..."
      - terraform init -input=false

  build:
    commands:
      - echo "Running Terraform Apply..."
      - terraform apply -auto-approve -input=false

  post_build:
    commands:
      - echo "Build completed on `date`"

# Uncomment the following if you are using artifacts
# artifacts:
#   files:
#     - '**/*'
