version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build process"
  build:
    commands:
      - echo "Build phase - nothing to build for HTML"
  post_build:
    commands:
      - echo "Post-build phase"
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
artifacts:
  files:
    - index2.html
  discard-paths: yes
  base-directory: .
rename:
  index2.html: index.html
